<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:context="http://www.springframework.org/schema/context"
    xmlns:aop="http://www.springframework.org/schema/aop" 
    xsi:schemaLocation="
        http://www.springframework.org/schema/beans 
        http://www.springframework.org/schema/beans/spring-beans.xsd
        http://www.springframework.org/schema/aop 
        http://www.springframework.org/schema/aop/spring-aop.xsd
        http://www.springframework.org/schema/context
        http://www.springframework.org/schema/context/spring-context.xsd"
        > <!-- bean definitions here -->
    <!-- <aop:aspectj-autoproxy/> -->
	<context:annotation-config/>
	<context:component-scan base-package="org.fage"></context:component-scan>
	
	<aop:config>
		 <!-- 声明一个切入类 -->
   		 <aop:aspect id="myAspect" ref="myAspect">
   		 <!-- 声明切面 -->
   		 <aop:pointcut id="servicePointcut" expression="execution(public * org.fage.service.UserService.*(..))"/>
   		 <!-- 也可以直接使用这个<aop:pointcut id="businessService" expression="org.fage.service.addUser(org.fage.domain.User)"/> -->
   		 <!-- 声明切入的advice --> 
   		 <!-- 方法之前 -->
   		 <aop:before pointcut-ref="servicePointcut" method="beforeMessage"/>
   		 <!-- 方法之后 -->
   		 <aop:after-returning pointcut-ref="servicePointcut" method="afterRunningMessage"/>
	     <!-- 方法抛出异常了切入 -->
	     <aop:after-throwing pointcut-ref="servicePointcut" throwing="RTexception" method="afterThrowingMessage"/>
    	 <!-- 无论异常还是不异常，类似finally做的事 -->
    	 <aop:after pointcut-ref="servicePointcut"  method="afterMessage"/>
    	 <!-- Around -->
    	 <aop:around pointcut-ref="servicePointcut" method="aroundMessage"/>
    	</aop:aspect>
	</aop:config>
	
	
	
	
</beans>